version: "3"
services:
  notebook:
    build: ./docker_images/jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    # command: /bin/sh -c "while :; do sleep 10; done"
      
    # command: start-notebook.sh --NotebookApp.token=''
